apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: springboot
  name: spring-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: springboot
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: 34.71.137.116:8083/demonginx1
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080 
      imagePullSecrets:
      - name: dockerreposecret
          
      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot
---
# Mongo host path deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo-svc
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
